ActionSet update and Added new Action Submit
arsalan-onschedule/adaptivecard-php pull request #1
Opened 2022-07-18 15:05 UTC by umer-onschedule

- Let ActionSet accept multiple actions correctly
- Add Action.Submit Adaptive Card action

2022-07-20 15:05 UTC, arsalan-onschedule requested changes

2022-07-20 15:05 UTC, arsalan-onschedule commented on src/Elements/Actions/Submit.php
> +        $this->data = json_encode($data);
Json encoding shouldn't be performed here. we required to encode whole class and we have written jsonSerialize function for it.

2022-07-20 15:05 UTC, arsalan-onschedule commented on src/Elements/Actions/Submit.php
> +        return json_decode($this->data);
since we won't encode here in the class, so this function wouldn't be required.

2022-07-20 15:05 UTC, arsalan-onschedule commented on src/Elements/Actions/ActionSet.php
> +        if($this->isAssoc($actions)){
We have setActions function separately so we dont required to duplicate the code.

2022-07-20 15:05 UTC, arsalan-onschedule commented on src/Elements/Actions/Submit.php
> +        $this->data = json_encode([]);
Don't need json_encode

2022-07-21 09:14 UTC, umer-onschedule commented on src/Elements/Actions/ActionSet.php
> +        if($this->isAssoc($actions)){
$this->setActions($actions);

2022-07-21 09:15 UTC, umer-onschedule commented on src/Elements/Actions/Submit.php
> +        $this->data = json_encode($data);
public function setData($data){
        $this->data = $data;
        return $this;
    }

2022-07-21 09:16 UTC, umer-onschedule commented on src/Elements/Actions/Submit.php
> +        return json_decode($this->data);
removed the conflicted code but the get/set functions are still included.
public function getData(){
        return $this->data;
    }

2022-07-21 09:17 UTC, umer-onschedule commented on src/Elements/Actions/Submit.php
> +        $this->data = json_encode([]);
public function jsonSerialize()
    {
        return [
            "type" => $this->getType(),
            "title" => $this->getTitle(),
            "style" => $this->getStyle(),
            "data" => $this->getData()
        ];
    }

2022-07-22 07:27 UTC, arsalan-onschedule approved these changes

2022-07-22 07:55 UTC, merged